spring:
  datasource:
    username: ${spring.datasource.db.user:root}
    url: jdbc:mysql://${spring.datasource.db.host:localhost}:3306/${spring.datasource.default_schema:99mall_inventory}?createDatabaseIfNotExist=true
    password: ${spring.datasource.db.password:Pikr@1991}
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp-relay.sendinblue.com
    username: touchblankspot@gmail.com
    password: 
    port: '587'
  thymeleaf:
    cache: false
server:
  port: 8086
encryption:
  remember_me:
    key: 3fZVNzasApraF509fhHT
    token:
      validity: 3600
  attribute:
    key: KdqZ01i0U7WF2J4OQqVjVCUIOCVrPoXh
    algorithm: AES
password:
  reset:
    token:
      validity_in_minute: 60
application:
  email:
    sender: touchblankspot@gmail.com

